### ISSUE TITLE
rendering a markdown page

### ISSUE THREAD

**Issue by laurentperrinet** [music-markdown/markdown-it-music#97]
Hi 

thanks for this great library!

I have compiled an anthology in 

https://github.com/laurentperrinet/brassens-md 

which I would like to simply render in

https://laurentperrinet.github.io/brassens-md/ 

without having to go to the (very nice and feature extensive) https://music-markdown.github.io/#/repos/laurentperrinet/brassens-md/viewer/master/brassens_mm.md

my question is : « is that possible ? »

(my main problem is that my knowledge of JS is very limited :-) but I am willing to learn)

cheers,
Laurent

**Comment by shadanan** [comment]
Bonjour Laurent

Je parle un petit peu le français. 

Merci d'avoir utiliser mon app! =)

Back to English. 

I don't think there's a way to get GitHub to use my markdown extension. If I could get that to work, I definitely would have done that first -- then I wouldn't have needed my own interface around the markdown viewer.

That being said, with some effort, it might be possible to make a browser extension that will render the markdown for you. Unfortunately, that means that the rendered markdown will only work in the browser where you've installed the extension.

**Comment by laurentperrinet** [comment]
Hi Shad,
merci pour le mot, ton français est excellent! :-)

back to english... 
to complement, it's certainly my lack of understanding of the inner working of rendering a page, but I thought that from a source (my markdown source), the HTML page was "compiled" through your package (just as you would using pandoc or LaTeX). What I mainly wish to have is just a way to render the position of the chords right as in 

<img width="786" alt="image" src="https://user-images.githubusercontent.com/381808/106380398-3c2f6680-63b2-11eb-89bc-c097501d042e.png">

instead of

<img width="726" alt="image" src="https://user-images.githubusercontent.com/381808/106380408-55381780-63b2-11eb-8258-2d4ec52c30cb.png">

(having the  chords by hovering the mouse is nice but not necessary)

I do not have a feeling as to how difficult it is to do that - I have looked at the mardown-it documentation to begin to have a sense. perhaps markdown-it-music could be used as a plugin?

cheers
Laurent

**Comment by shadanan** [comment]
Hi Laurent,

So the main challenge is that I don't know of a way to get pages on GitHub to use a markdown plugin.

That being said, if you only want to be able to render your music with the chords correctly aligned, you can achieve that by wrapping your verses in a code fence (```), the same way that you can render other code blocks.

The only issue with this is that it will no longer render using my renderer on the music markdown page. It will instead use the code fence renderer.

Does this solution work for you?

**Comment by laurentperrinet** [comment]
Hi Shad,

sounds like a good solution. I'm already a script ( https://github.com/laurentperrinet/brassens-md/blob/master/brassens.py ) to convert the original markdown ( https://github.com/laurentperrinet/brassens-md/blob/master/README.md ) into one compatible with your library ( https://github.com/laurentperrinet/brassens-md/blob/master/brassens_mm.md ). it notably transforms chords from french to english notation ("La" -> "A", ...)

to render the markdown file as html, I have tried using

```

text = ''
with open('brassens_mm.md','r') as f:
    for line in f:
        text += line

# WRITE
def write(lines, fname='brassens_mm.md'):
    with open(fname,'w') as f:
        for line in lines:
            f.write(line)

from markdown_it import MarkdownIt
from markdown_it.extensions.front_matter import front_matter_plugin
from markdown_it.extensions.footnote import footnote_plugin
md = (
MarkdownIt()
.use(front_matter_plugin)
.use(footnote_plugin)
.enable('table')
)

write(md.render(text), 'index.html')

```
(where `text` is the markdown file imported as strings)

but I do not know how to use your plugin there... I think we are getting close...

Cheers,
Laurent

**Comment by shadanan** [comment]
Hey Laurent. I'll have some time to look at this this weekend and I'll find you an easy solution.

**Comment by shadanan** [comment]
Hey Laurent,

So, based on what I've seen so far, you have two options.

1. You can include the markdown-it and markdown-it-music plugin in an HTML file directly and use it to render some code when you open the page.
2. Or you can use the markdown-it plugin to render the HTML already fully formatted. 

Which option do you prefer?

If you prefer to use the markdown-it-music plugin in an HTML file directly, you can follow how I use it in the music-markdown code here:
https://github.com/music-markdown/music-markdown/blob/master/src/components/MusicMarkdown.js#L10

Here's the relevant code bits:

```js
import MarkdownIt from "markdown-it";
import MarkdownItMusic from "markdown-it-music";

const MD = new MarkdownIt({ html: true }).use(MarkdownItMusic);
const html = MD.render(source)
```

There's a slight caveat. My library depends on a browser being present.

If on the other hand you just want the final output, I'm thinking of add a CLI to markdown-it-music that you can call, something like:

```shell
$ musicmd <input markdown file> <output html file>
```

This will require a bit of effort on my part to replace the browser dependent bits of code in the library. I was hoping to get that done for you this weekend, but it might take me a bit more time than that.

What do you think?

Cheers,
Shad

**Comment by laurentperrinet** [comment]
Hi Shad,

Thanks a lot for the time you take, especially to explain the different bits, it's very valuable. Of course, the second option (having a CLI) would be the best, and I am ready to assist if needed. 

When you say that "library depends on a browser being present", do you mean that some of the web page is rendered by it?

Thanks,
Laurent

**Comment by shadanan** [comment]
Hey Laurent,

Good news, I managed to get a CLI working. It's still in pretty rough shape, but I think I'll have a more polished version of the library available on npm by tomorrow.

A lot of the dependent javascript code uses globals that are only available in a browser. For example, `document` and `window`.

I found some other libraries that emulate those objects when not running in a browser.

I'll send you more instructions on how to use the new CLI once I published the updated npm.

Cheers,
Shad

**Comment by laurentperrinet** [comment]
hey Shad,

great news! I am looking forward to beta-test it :-)

cheers,
Laurent

On 8 Feb 2021, at 10:23, Shad Sharma <notifications@github.com<mailto:notifications@github.com>> wrote:



Hey Laurent,

Good news, I managed to get a CLI working. It's still in pretty rough shape, but I think I'll have a more polished version of the library available on npm by tomorrow.

A lot of the dependent javascript code uses globals that are only available in a browser. For example, document and window.

I found some other libraries that emulate those objects when not running in a browser.

I'll send you more instructions on how to use the new CLI once I published the updated npm.

Cheers,
Shad

**Comment by shadanan** [comment]
Hi Laurent,

I got a [new version (0.0.19)](https://www.npmjs.com/package/markdown-it-music/v/0.0.19) of the library deployed which now has CLI support. I updated the [README](https://github.com/music-markdown/markdown-it-music/#cli) with usage instructions.

Here's a demo of the CLI in use:
![musicmd-cli](https://user-images.githubusercontent.com/361429/107319222-34775e00-6a53-11eb-8ce3-b366eb96c383.gif)

Let me know how it goes. Also, feel free to take a look at the [implementation](https://github.com/music-markdown/markdown-it-music/pull/98). Before you filed this issue, I wasn't aware that guitar tablature was different in French. I was thinking it would be nice to support chords in other languages. If you wanted to help me with that, I could teach you how to make changes to the library.

Thanks for beta testing for me!
Shad

**Comment by laurentperrinet** [comment]
Hi Shad,

thanks a lot, it works perfectly, just like in your demo! I'm impressed!

I gave it a shot @ https://laurentperrinet.github.io/brassens-md/ (now I have to spilt the discography into albums, but that is another subject...). Regarding the implementation, I could read but javascript reads a bit like dutch to me :-) I will try to include music scores in my music sheet, that looks really good in the "A Bar in Amsterdam - Katzenjammer" page.

Concerning support for chords in other languages (Basically that C-D-E-F-A-B-C transforms to Do-Ré-Mi-Fa-Sol-La-Si-Do), would you like me to open a new issue?

Cheers,
Laurent

**Comment by shadanan** [comment]
Hey Laurent,

I'm really glad it worked and I'm very happy to have a customer other than myself. =)

I understand now what you mean by chords in other languages -- Do-Ré-Mi -- we call that solfege. It is a way to represent notes relative to a key. It doesn't really map 1-to-1 with guitar chords, so supporting it will require a lot of thought.

If you have some notion how we can best support solfege, feel free to open up a new issue and we can work out a design together that accommodates it.

I'll go ahead and close this one.

Kind regards,
Shad

**Comment by laurentperrinet** [comment]
Thanks a lot ! For the solfege I just self-learned it  and the mapping I did in my script isn’t really one to one - more thoughts need to go there ...
